### ISSUE TITLE
Reverting to Vita MC if no SD card inserted

### ISSUE THREAD

**Issue by VgaCich** [xyzz/gamecard-microsd#21]
Mount original Vita MC as ux0: if no SD card inserted.

**Comment by stuermera** [comment]
Has this been fixed with the 1.3 release of gamesd? :) Thx

**Comment by xyzz** [comment]
No

**Comment by KupoAuster** [comment]
Not yet fixed.
And here I was thinking it was a good option.

**Comment by CelesteBlue-dev** [comment]
https://github.com/CelesteBlue-dev/PSVita-StorageMgr does that.
